// Generated by 'unplugin-vue-dotenv'
// We suggest you to commit this file into source control

/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly asd: string
  readonly NODE_ENV: string
  readonly ooo: string
  readonly VITE_AAA: string
  readonly VITE_BBB: string
  readonly VITE_ccc: string
  readonly VITE_TEST_KEY: string
  readonly VITE_TEST_URl: string
  readonly VITE_test_url_ABC: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
